export const AuthConstants = {
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILE: 'LOGIN_FAILE',

    LOGOUT_REQUEST: 'LOGOUT_REQUEST',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGOUT_FAILE: 'LOGOUT_FAILE',

    REGISTER_REQUEST: 'REGISTER_REQUEST',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAILE: 'REGISTER_FAILE',

    GET_VERIFY_CODE_REQUEST: 'GET_VERIFY_CODE_REQUEST',
    GET_VERIFY_CODE_SUCCESS: 'GET_VERIFY_CODE_SUCCESS',
    GET_VERIFY_CODE_FAILE: 'GET_VERIFY_CODE_FAILE',

    CHECK_VERIFY_CODE_REQUEST: 'CHECK_VERIFY_CODE_REQUEST',
    CHECK_VERIFY_CODE_SUCCESS: 'CHECK_VERIFY_CODE_SUCCESS',
    CHECK_VERIFY_CODE_FAILE: 'CHECK_VERIFY_CODE_FAILE',

    GET_PROFILE_REQUEST: 'GET_PROFILE_REQUEST',
    GET_PROFILE_SUCCESS: 'GET_PROFILE_SUCCESS',
    GET_PROFILE_FAILE: 'GET_PROFILE_FAILE',

}