export const PostConstant = {
    CHANGE_LIKE_REQUEST: 'CHANGE_LIKE_REQUEST',
    CHANGE_LIKE_SUCCESS: 'CHANGE_LIKE_SUCCESS',
    CHANGE_LIKE_FAILE: 'CHANGE_LIKE_FAILE',

    GET_POST_BY_USER_REQUEST: 'GET_POST_BY_USER_REQUEST',
    GET_POST_BY_USER_SUCCESS: 'GET_POST_BY_USER_SUCCESS',
    GET_POST_BY_USER_FAILE: 'GET_POST_BY_USER_FAILE',

    GET_LIST_POST_REQUEST: 'GET_LIST_POST_REQUEST',
    GET_LIST_POST_SUCCESS: 'GET_LIST_POST_SUCCESS',
    GET_LIST_POST_FAILE: 'GET_LIST_POST_FAILE',

    UN_LIKE_REQUEST: 'UN_LIKE_REQUEST',
    UN_LIKE_SUCCESS: 'UN_LIKE_SUCCESS',
    UN_LIKE_FAILE: 'UN_LIKE_FAILE',

    GET_COMMENT_POST_REQUEST: 'GET_COMMENT_POST_REQUEST',
    GET_COMMENT_POST_SUCCESS: 'GET_COMMENT_POST_SUCCESS',
    GET_COMMENT_POST_FAILE: 'GET_COMMENT_POST_FAILE',

    ADD_COMMENT_POST_REQUEST: 'ADD_COMMENT_POST_REQUEST',
    ADD_COMMENT_POST_SUCCESS: 'ADD_COMMENT_POST_SUCCESS',
    ADD_COMMENT_POST_FAILE: 'ADD_COMMENT_POST_FAILE',

    CREATE_POST_REQUEST: 'CREATE_POST_REQUEST',
    CREATE_POST_SUCCESS: 'CREATE_POST_SUCCESS',
    CREATE_POST_FAILE: 'CREATE_POST_FAILE',

    REPORT_POST_REQUEST: 'REPORT_POST_REQUEST',
    REPORT_POST_SUCCESS: 'REPORT_POST_SUCCESS',
    REPORT_POST_FAILE: 'REPORT_POST_FAILE',

    GET_POST_REQUEST: 'GET_POST_REQUEST',
    GET_POST_SUCCESS: 'GET_POST_SUCCESS',
    GET_POST_FAILE: 'GET_POST_FAILE',

    CHANGE_AVATAR_REQUEST: 'CHANGE_AVATAR_REQUEST',
    CHANGE_AVATAR_SUCCESS: 'CHANGE_AVATAR_SUCCESS',
    CHANGE_AVATAR_FAILE: 'CHANGE_AVATAR_FAILE',

}